name: Database Migrations with Flyway

on:
  # push:
  #   branches: [ "main" ]
  #   paths:
  #     - 'src/migrations/**'
  workflow_dispatch:

jobs:
  FlywayMigration:
    name: Run Flyway Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute Flyway Migrations
        run: |
          docker run --rm \
            --volume ${GITHUB_WORKSPACE}/src/migrations:/flyway/sql:ro \
            redgate/flyway \
            -url="jdbc:postgresql://${{ vars.DB_HOST }}:${{ vars.DB_PORT }}/polylingo_db?sslmode=require" \
            -user="${{ vars.DB_USER }}" \
            -password="${{ secrets.DB_PASSWORD }}" \
            migrate
